### ISSUE TITLE
Rollout plan for critical projects 2FA requirement

### ISSUE THREAD

**Issue by di** [pypi/warehouse#12308]
Breaking this out from #11625. The following steps should be followed to roll out the critical projects 2FA requirement:

- [ ] Resolve https://github.com/pypi/warehouse/issues/11850
- [ ] Evaluate how many critical project maintainers will be affected by enabling the mandate.
  - Ideally this is non-zero, but likely that some projects/maintainers may be unresponsive
  - Depending on the size, potentially do some manual comms to affected maintainers
- [ ] Set `TWOFACTORMANDATE_ENABLED` to `True`
  - This makes 2FA required for critical projects and completes the rollout
- [ ] Tweets/announcements about this milestone
