### ISSUE TITLE
Meta: Frontend Improvements

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#12334]
A wishlist/collection of ideas that would be beneficial to support rapid frontend development on the warehouse codebase.

## ✅ Node Runtime Version

NodeJS 14 is in Maintenance mode, and becomes [end of life in April 2023](https://endoflife.date/nodejs).

- [x] Upgrade past Node 14 to 16 (LTS). Updates to `package-lock.json`, `Dockerfile`, `Dockerfile.static`, and any related docs: https://github.com/pypi/warehouse/pull/12288
- [x] remove [entry from package.json](https://github.com/pypi/warehouse/blob/3a3e54dbf23536e084929a45dec1179fca5006df/package.json#L63) and [test setup](https://github.com/pypi/warehouse/blob/39daea188d2e1e6494c50753cd48cb5a8da3e8c4/tests/frontend/setup.js#L46-L47): https://github.com/pypi/warehouse/pull/12379
    [node-webcrypto-ossl](https://www.npmjs.com/package/node-webcrypto-ossl) (used solely in tests) emits a pile of compilation warnings during install. It has been deprecated as of Node 15, replaced by built-in `window.crypto` capability.
- [x] remove other unnecessary libraries as a result of other upgrade tasks https://github.com/pypi/warehouse/pull/12379
- [x] update any other easy-to-update dependencies that we expect to continue using https://github.com/pypi/warehouse/pull/12458
    - Replace uglify-js with [terser](https://terser.org/). Uglify-js doesn't support ES6 without passing it through other transpiliers like Babel, and we're targeting our own ES6 and more dependencies are moving to ES6, making the Babel config that much more complex. Webpack itself uses Terser, as does Parcel and others..

## ✅  Build Tooling

- [x] upgrade to webpack 5 - #12715
- [x] (**big**) replace gulp with webpack - #12728 #12742
    See prior work in #6141

## Stimulus JS

- [x] Upgrade to version 3.x and update code/tests to conform - https://github.com/pypi/warehouse/pull/12558
    We’ve chosen [Stimulus JS](https://stimulus.hotwired.dev/) as our main JavaScript framework as it’s relatively lightweight, hooks on to HTML `data` attributes pretty well.  The current supported version (and available documentation is for `@hotwired/stimulus` v3.x.
    We’re on 2.x after [I attempted an upgrade to 3](https://github.com/pypi/warehouse/pull/11808), and stopped when I hit a pile of other blockages along the way (I forgot to document what happened, but may try again sometime soon).
- [x] Replace `clipboard` code with browser native APIs via Stimulus, remove dependency
    We install external dependency [`clipboard`](https://github.com/pypi/warehouse/blob/3a3e54dbf23536e084929a45dec1179fca5006df/package.json#L22) to support [click-copy](https://github.com/pypi/warehouse/blob/3a3e54dbf23536e084929a45dec1179fca5006df/warehouse/static/js/warehouse/index.js#L76-L107), probably prior to wide adoption of browser APIs.
    - #13353 
    - #13565

A lot of JavaScript functions in [`index.js`](https://github.com/pypi/warehouse/blob/3a3e54dbf23536e084929a45dec1179fca5006df/warehouse/static/js/warehouse/index.js) are non-Stimulus and loaded via [`docReady`](https://github.com/pypi/warehouse/blob/3a3e54dbf23536e084929a45dec1179fca5006df/warehouse/static/js/warehouse/utils/doc-ready.js).
See https://github.com/pypi/warehouse/issues/3144 for an example.

- [x] Convert Change Role code to Stimulus controller #3144 - #12707

## Misc

- [x] Emit Jest Coverage metadata during static tests - #12665
- [x] Modernize Admin website - #12747
- [x] Remove deprecated `@babel/polyfill` and other unused Babel code - #12758
- [x] Replace deprecated `sass-lint` with `stylelint` - #12774

**Comment by dstufft** [comment]
Is this issue done? It looks like all the tasks are checked off :D

**Comment by miketheman** [comment]
Yep, I think I’m happy where we ended up for now.

There are still a fair amount of unconverted JavaScript code in the main js module and utils, but nothing is stopping this from being routine refactorings.

**Comment by di** [comment]
Thanks @miketheman for all your great work here!
