### ISSUE TITLE
[meta] Update database-centric libraries

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#13497]
We've got newer libraries to look at for database accesses, and need a sane workflow to get us to the finish line.

Here's an outline of execution:

- [x] Upgrade to latest SQLAlchemy 1.4.x - done - we're on 1.14.47
- [x] Run tests with `SQLALCHEMY_WARN_20=1` to surface all Deprecation warnings, resolve those post-haste
   - [x] #13511 
   - [x] #13784 
   - [x] #13785
   - [x] #13845
   - [x] #13895
- [x] Set `future=True` on `sessionmaker` & `create_engine` and run tests
	- [x] Fails on session passing [in `Event.ip_address` magic](https://github.com/pypi/warehouse/blob/47a4e033332f83f59548022066f94a86d4f22084/warehouse/events/models.py#L177C1-L190), which we should probably remove after every Event has a related `IPAddress` (see #13804 #13823 #13842)
	- [x] Fails on test case. Refactor: #13889
- [x] Upgrade to SQLalchemy 2.0.16 https://github.com/pypi/warehouse/pull/13929
  - [x] #13942
  - [x] Read https://docs.sqlalchemy.org/en/20/changelog/migration_20.html
  - [x] Replace `sqlalchemy-citext` as it's no longer needed, there's a built-in https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#sqlalchemy.dialects.postgresql.CITEXT
  - [x] #13948
  - [x] #13950
- [x] Upgrade `psycopg3` - see https://github.com/pypi/warehouse/pull/10742
- [x] Upgrade `pytest-postgresql` to 5.x
- [x] Celebrate!

**Comment by miketheman** [comment]
As of today, we've updated all the libraries and associated code to make them work.

There's still outstanding work to convert to SQLAlchemy 2.0 ORM PEP-484 support, but that can be completed outside this work.

Major kudos to @di, @ewdurbin , @dstufft for all their work on making this happen!
